region = "europe-west3"
region_zone = "europe-west3-b"
project_name = "quantum-bus-develop-5920ae26"
credentials_file_path = "~/.gcloud/Terraform.json"
public_key_path = "~/.ssh/gcloud_id_rsa.pub"
private_key_path = "~/.ssh/gcloud_id_rsa"
